### ISSUE TITLE
Date inconsistentcty report for 2081 

### ISSUE THREAD

**Issue by fooldevoloper** [sbmdkl/nepali-datepicker-reactjs#17]
**Calendar  Inconsistent Report**
**Jestha 32 ->>>> Missing
Asar 32 ->>>> Unnecessary
Poush 29 ->>>>> Unnecessary
Falgun (29-30) ->>>>>  Unnecessary
Chaitra 31 ----- Missing  from calendar**

**Comment by sbmdkl** [comment]
Fixed by: https://github.com/sbmdkl/nepali-datepicker-reactjs/pull/16
