### ISSUE TITLE
Incorrect Number of days in bs array

### ISSUE THREAD

**Issue by pokhrelrewant** [sbmdkl/nepali-datepicker-reactjs#18]
Incorrect Number of days in bs array in 2081 BS for months Jestha, Ashar, Falgun and Chaitra.

**Comment by sbmdkl** [comment]
Hi @pokhrelrewant - its correct in the latest version.
Can you share the screenshots with the incorrect numbers of days and the expected days?

**Comment by pokhrelrewant** [comment]
Thank you, I was using the 1.2.1 version. It's working correctly now after I updated it.
