### ISSUE TITLE
<form> cannot appear as a descendant of <form>

### ISSUE THREAD

**Issue by Parasbuda** [sbmdkl/nepali-datepicker-reactjs#2]
While using with formik it is rising the issue...Can u resolve this......
https://codesandbox.io/s/thirsty-wright-3rv3n?file=/src/App.js

**Comment by sbmdkl** [comment]
This issue has been resolved now. please update to the latest version (at this time: 1.0.8)

**Comment by Parasbuda** [comment]
thanks alot man
