### ISSUE TITLE
default value of date picker

### ISSUE THREAD

**Issue by narendrachettri** [sbmdkl/nepali-datepicker-reactjs#7]
i want a value from date picker only when i select a date. It's giving a default value which i don't want. Can you help on this

**Comment by sbmdkl** [comment]
Hi @narendrachettri, thanks for creating this issue.
You can now have the feature to hideDefaultValue and have your own placeholder @ version >= 1.2.0
pass `hideDefaultValue` as a props to Calendar component.

```
        <Calendar
          hideDefaultValue={true}
          placeholder="मिति छान्नुहोस्"
          onChange={this.onChange}
        />
```

demo:
https://codesandbox.io/s/friendly-keller-0vyjq?file=/src/App.js

**Comment by narendrachettri** [comment]
it's not solved yet. onChange function getting bsDate and adDate value
without changing the value. Check it once. It's taking current date inside
a onchange function. Can you fix this. Because it will submit a current
date even i left it blank, which i am getting an issue with. Even you can
check it on sandbox by doing console log you will understand where the
problem is otherwise everything is great.

**Comment by narendrachettri** [comment]
check this out you will know the problem. Behind the scene it's triggering
onchange on first render and giving current date value. by which if i
submit the form without taking a value from datepicker it will give me a
current date. which is inefficient and force me to insert a false data. Can
you fix this problem.
